# Generated by Django 2.2.16 on 2020-09-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='demo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_demo', to='home.NewModel'),
        ),
    ]
